### ISSUE TITLE
grunt zip contains subfolders

### ISSUE THREAD

**Issue by Shawful** [twolfson/grunt-zip#36] opened 2015-04-28 20:54 UTC
I am created a yeoman project which I plan to zip and deploy to an AWS s3 bucket.

I'm taking everything within the 'dist' or distribution folder, zipping it up, and I've noticed that it does in fact create a *.zip file and place it in the correct destination path.

My problem is that when I upzip said *.zip file, it includes a 'dist' folder at the top of the folder tree and then beneath that folder are all of the compressed web files for the project, the goodies of the project.  

I would like to place all of the compressed web files at the top level of the project, instead of being contained within the dist folder.

Is there a recommended way to accomplish this task?

**Comment by twolfson** [comment] 2015-04-29 03:15
This is a duplicate of #22. To remove the `dist/` while zipping, we can use the `cwd` option to indicate that we want to copy the contents of `dist/` but not `dist/` itself:

```js
{
  zip: {
    cwd: 'dist/',
    src: '**/*',
    dest: 'dist.zip'
  }
}
```

**Closed by twolfson** 2015-04-29 03:15 UTC

**Comment by Shawful** [comment] 2015-04-29 14:18
I just realized that I need a different directory structure.  Instead of moving all of the "goodies" up a folder level, I need to replace the dist folder with a folder of a different name, and keep the current structure.  Is there a way to accomplish this?  I appologize for the confusion.  My understanding of the file folder structure that was needed for this project was incorrect.

**Comment by twolfson** [comment] 2015-04-29 20:49
`cwd` is explained in the documentation with an example:

https://github.com/twolfson/grunt-zip/tree/0.16.2#using-cwd

For the renamed folder case, you can:

- Rename/copy the folder to `new-folder` and use the original configuration you had
- Use `router` to dynamically rename the path (e.g. `filepath.replace(/^dist/, 'new-folder')`)
    - Documentation can be found here: https://github.com/twolfson/grunt-zip/tree/0.16.2#using-router

**Comment by Shawful** [comment] 2015-04-29 21:32
I did get it to work, but I needed to modify <code>src: '*****/ *'</code> to <code>src: 'dist/*****'</code>, instead of what you suggested above because this code allows me to grab <b>only</b> the files from my distribution folder and keep them at the top level of my *.zip file.

Also, the suggestion above does not match the literature in the readme.md file.  Using <code>src: '***/**'</code>, will grab a lot of extra files that I do not need (outside of my distribution folder). 

Also, I noticed that the readme.md file is missing a comma after <code>cwd: 'nested/'</code> on the main github page.  Would you please add this comma when you get a chance.  I'm sure others will appreciate it. 

Readme.md - (missing a comma after cwd: 'nested/')
![image](https://cloud.githubusercontent.com/assets/5322272/7400820/344f00a4-ee85-11e4-9c57-49e838ed46eb.png)
